### ISSUE TITLE
Allow setting default shell option

### ISSUE THREAD

**Issue by TAG-Epic** [nooproject/noo#2]
Currently there is no way to customize the --shell option in noo clone. 
This is not ideal as all my noofiles uses shell and I trust my noofiles to be safe.

Maybe add a noo config file to allow for this?

**Comment by vcokltfre** [comment]
Implemented in [this](https://github.com/py-noo/noo/commit/9b58b966cf31e72e3fcd1b3ad1ce83cccd7e9022) commit
