### ISSUE TITLE
Refactor Registry

### ISSUE THREAD

**Issue by TAG-Epic** [nooproject/noo#4]
The registry currently uses `get_item` and `set_item` functions instead of `__getitem__` and `__setitem__` which imo is messier.
Considering #2 would need a bit of a refactor to avoid copy pasting the entire class.

Possibly change `NOO_REGISTRY_PATH` to `XDG_CONFIG_HOME` [docs](https://wiki.archlinux.org/title/XDG_Base_Directory)?

**Comment by vcokltfre** [comment]
I don't use XDG, nor does anyone on Windows or Mac

**Comment by vcokltfre** [comment]
As discussed in Discord, I'll implement this, and then you'll be able to do #2 since the required framework will be in place

**Comment by vcokltfre** [comment]
Done in [this](https://github.com/py-noo/noo/commit/7d3045dff882bb5a966e73eaf5b079474f00f678) commit
